import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../globals.css";
import NextTopLoader from "nextjs-toploader";
import Link from "next/link";
import { Package2, PanelLeft, Search, Settings } from "lucide-react";

import { Button } from "@/components/ui/button";

import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
  TooltipProvider,
} from "@/components/ui/tooltip";
import { auth } from "@/auth";
import { roleType } from "@/lib/types";
import Accordion from "@/components/accordion";
import { groupRoute } from "@/helpers/utils";
import { Toaster } from "@/components/ui/toaster";
import LogoutForm from "@/components/auth/logoutForm";
const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const displayRoute = session?.user.roles.filter(
    (item: roleType) => !item.duongdan.endsWith("/")
  );
  const groupRoutes = groupRoute(displayRoute);
  return (
    <html lang="vi">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <aside className="fixed inset-y-0 left-0 z-10 hidden w-52 shadow-md bg-white flex-col border-r bg-background sm:flex">
            <nav className="flex flex-col items-start gap-4 px-4 sm:py-5">
              <Link
                href="#"
                className="group flex h-9 w-9 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:h-8 md:w-8 md:text-base"
              >
                <Package2 className="h-4 w-4 transition-all group-hover:scale-110" />
                <span className="sr-only">Acme Inc</span>
              </Link>

              <ul className="space-y-2 font-medium">
                {groupRoutes &&
                  groupRoutes.map((item) => {
                    if (Array.isArray(item)) {
                      return (
                        <li key={item[0].id + item[0].ten} className="">
                          <Accordion title={`Quản lý ${item[0].ten}`}>
                            {item.map((route) => (
                              <li key={route.id}>
                                <Link
                                  href={route.duongdan}
                                  className="flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg pl-6 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700"
                                >
                                  {route.ten}
                                </Link>
                              </li>
                            ))}
                          </Accordion>
                        </li>
                      );
                    }
                    return (
                      <li key={item.id}>
                        <Link
                          href={item.duongdan}
                          className="flex items-center py-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
                        >
                          <span className="ms-3">{item.ten}</span>
                        </Link>
                      </li>
                    );
                  })}
              </ul>
            </nav>
            <nav className="mt-auto flex flex-col items-start gap-4 px-4 sm:py-5">
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Link
                      href="#"
                      className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
                    >
                      <Settings className="h-5 w-5" />
                      <span className="sr-only">Settings</span>
                    </Link>
                  </TooltipTrigger>
                  <TooltipContent side="right">Settings</TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </nav>
          </aside>
          <div className="relative flex flex-col sm:gap-4 sm:py-4 sm:pl-52">
            <header className="flex items-center gap-4 border-b  px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
              <Sheet>
                <SheetTrigger asChild>
                  <Button size="icon" variant="outline" className="sm:hidden">
                    <PanelLeft className="h-5 w-5" />
                    <span className="sr-only">Toggle Menu</span>
                  </Button>
                </SheetTrigger>
                <SheetContent side="left" className="sm:max-w-xs bg-white">
                  <nav className="grid gap-6 text-lg font-medium ">
                    <Link
                      href="#"
                      className="group flex h-10 w-10 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:text-base"
                    >
                      <Package2 className="h-5 w-5 transition-all group-hover:scale-110" />
                      <span className="sr-only">Acme Inc</span>
                    </Link>
                    {session?.user?.roles &&
                      session?.user?.roles.map((item: roleType) => (
                        <Link key={item.id} href={item.duongdan}>
                          <h4 className="md:text-base text-sm text-zinc-900">
                            {item.ten}
                          </h4>
                        </Link>
                      ))}
                  </nav>
                </SheetContent>
              </Sheet>
              <div className="relative ml-auto flex-1 md:grow-0">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="Tìm kiếm..."
                  className="w-full rounded-lg  bg-background  pl-8 md:w-[200px] lg:w-[336px]"
                />
              </div>
              <LogoutForm />
            </header>
            <div className="">{children}</div>
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
